apiVersion: v1
kind: PersistentVolume
metadata:
  name: vector-data-pv
  labels:
    apps: vector-collector
    product: openshift
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: local-nfs-sc
  nfs:
    path: /data/nfs/vector
    server: nas.ocp4.ybkim.local
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vector-data-pvc
  namespace: vector
  labels:
    app: vector-collector
    product: openshift
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: vector-data-pv
  volumeMode: Filesystem
