apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana-oss
    product: openshift
  name: kibana-oss
  namespace: vector
spec:
  ports:
  - name: 5601-tcp
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana-oss
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kibana-oss
    product: openshift
  name: kibana-oss
  namespace: vector
spec:
  host: kibana-vector.apps.ocp4.ybkim.local
  port:
    targetPort: 5601-tcp
  to:
    kind: Service
    name: kibana-oss
    weight: 100
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kibana-oss
    product: openshift
  name: kibana-oss
  namespace: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-oss
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana-oss
        product: openshift
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana-oss:7.10.2
        imagePullPolicy: IfNotPresent
        name: kibana-oss
        ports:
        - containerPort: 5601
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
